name: Sync Upstream

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/armando-ncg/merge-strategy-forked.git"
  # Required, token to authenticate bot, could use ${{ secrets.GITHUB_TOKEN }}
  # Over here, we use a PAT instead to authenticate workflow file changes.
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  # Optional, defaults to main
  UPSTREAM_BRANCH: "main"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "main_upstream"
  ORG: "alejandrojn-ncg"

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
#    - name: GitHub Sync to Upstream Repository
#      id: sync
#      uses: dabreadman/sync-upstream-repo@v1.3.0
#      with:
#        upstream_repo: ${{ env.UPSTREAM_URL }}
#        upstream_branch: ${{ env.UPSTREAM_BRANCH }}
#        downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
#        token: ${{ env.WORKFLOW_TOKEN }}
#        fetch_args: ${{ env.FETCH_ARGS }}
#        merge_args: ${{ env.MERGE_ARGS }}
#        push_args: ${{ env.PUSH_ARGS }}
#        spawn_logs: ${{ env.SPAWN_LOGS }}
#

    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync Upstream Repo
      run: ./sync.sh ${{ env.UPSTREAM_URL }} ${{ env.UPSTREAM_BRANCH }} ${{ env.DOWNSTREAM_BRANCH }} ${{ env.WORKFLOW_TOKEN }} ${{ env.ORG }}

    - name: Verify if new content
      run: |
        echo $MERGE_RESULT

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        ref: ${{ env.DATE }}_upstream

    - name: Create PR
      if: ${{ env.MERGE_RESULT != 'Already up to date.' }}
      uses: devops-infra/action-pull-request@v0.5.0
      with:
        github_token: ${{ env.WORKFLOW_TOKEN }}
        source_branch: ${{ env.DATE }}_upstream
        target_branch: main 
        title: New Upstream
        #template: .github/PULL_REQUEST_TEMPLATE.md
        body: "**Automated pull request**"
        #reviewer: octocat
        #assignee: octocat
        #label: enhancement
        #milestone: My milestone
        #draft: true
        #old_string: "<!-- Add your description here -->"
        new_string: "** Automatic pull request**"
        get_diff: false
        #ignore_users: "dependabot"
        allow_no_diff: true

